name: my-music

services:
  postgres:
    image: postgres:18.4
    ports:
      - 56432:5432
    environment:
      POSTGRES_USER: my_music
      POSTGRES_PASSWORD: my_music
      POSTGRES_DB: my_music
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
