query FindAlbums($input: QueryAlbumsInput!) {
  albums(input: $input) {
    id
    artist
    title
    year
    firstPlayed {
      ... on FirstPlayedTime {
        timestamp
      }
      ... on FirstPlayedDate {
        year
        month
        day
      }
    }
  }
}
