-- AlterTable
ALTER TABLE "album_sources" ALTER COLUMN "accurate_rip" SET DATA TYPE TEXT,
ALTER COLUMN "comments" SET DATA TYPE TEXT,
ALTER COLUMN "cue_issues" SET DATA TYPE TEXT,
ALTER COLUMN "download" SET DATA TYPE TEXT,
ALTER COLUMN "edition" SET DATA TYPE TEXT,
ALTER COLUMN "tag_issues" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "albums" ALTER COLUMN "artist" SET DATA TYPE TEXT,
ALTER COLUMN "comments" SET DATA TYPE TEXT,
ALTER COLUMN "title" SET DATA TYPE TEXT;
