name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Migrate typegen database
        run: pnpm db:migrate:prod
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.TYPEGEN_DATABASE_URL }}
          DIRECT_DATABASE_URL: ${{ secrets.TYPEGEN_DATABASE_URL }}

      - name: Generate Prisma client
        run: pnpm prisma:generate
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.TYPEGEN_DATABASE_URL }}
          DIRECT_DATABASE_URL: ${{ secrets.TYPEGEN_DATABASE_URL }}

      - name: Generate Relay types
        run: pnpm generate:graphql

      - name: Pull Vercel Environment Information
        run: pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Migrate production database
        run: pnpm db:migrate:prod
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DIRECT_DATABASE_URL }}
          DIRECT_DATABASE_URL: ${{ secrets.DIRECT_DATABASE_URL }}

      - name: Deploy Project Artifacts to Vercel
        run: pnpm vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
